Start Date:
  type: date
End Date:
  type: date
UPC:
  exclude: true
ISRC/ISBN:
  exclude: true
ISRC:           
  exclude: true
Vendor Identifier:
Quantity:
  type: integer
Partner Share:
  type: currency
Extended Partner Share:
  type: currency
Partner Share Currency:
  heading: Currency
  total_amount_currency: true  # Do not remove this!
Sales or Return:
Sale or Return:
Apple Identifier:
Artist/Show/Developer/Author:
  heading: Developer
  exclude: true
Artist/Show/Developer:
  heading: Developer
  exclude: true
Title:
  exclude: true
Label/Studio/Network/Developer/Publisher:
  exclude: true
Label/Studio/Network/Developer:
  exclude: true
Label/Studio/Network:
  exclude: true
Side:
  exclude: true
Grid:
  exclude: true
Product Type Identifier:
  heading: Product Type ID
ISAN/Other Identifier:
  exclude: true       
Account Identifier:
  exclude: true
Country Of Sale:
Pre-order Flag:
Prepaid:
  exclude: true
Prepaid Type:
  exclude: true
CMA Flag:
  exclude: true
Promo Code:
Customer Price:
  type: currency
Customer Currency:
  heading: Currency
